//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSaleDirectionResponsibles
    {
        public int Id { get; set; }
        public string UserSid { get; set; }
        public int SaleDirectionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorSid { get; set; }
        public string UserEmail { get; set; }
    
        public virtual ProjectSaleDirections ProjectSaleDirections { get; set; }
    }
}
