//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientInn { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> SaleDirectionId { get; set; }
        public Nullable<int> SaleSubjectId { get; set; }
        public Nullable<int> Probability { get; set; }
        public string ManagerSid { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> ManagerDepartmentId { get; set; }
        public string ManagerDepartmentName { get; set; }
        public string ManagerChiefSid { get; set; }
        public string ManagerChiefName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorSid { get; set; }
        public string CreatorName { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleterSid { get; set; }
        public string DeleterName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> StateChangeDate { get; set; }
        public string ChangerSid { get; set; }
        public string ChangerName { get; set; }
        public Nullable<bool> IsAuction { get; set; }
        public Nullable<System.DateTime> TkpDeadlineDate { get; set; }
        public string DeadlineDate { get; set; }
        public Nullable<System.DateTime> AuctionDeadlineDate { get; set; }
        public Nullable<int> ConditionId { get; set; }
        public Nullable<int> BusinessTargetId { get; set; }
        public string BusinessTargetName { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<bool> CurrentYearRealization { get; set; }
        public Nullable<bool> HasBudget { get; set; }
        public Nullable<int> ClientRelationshipId { get; set; }
        public string Comment { get; set; }
    }
}
