//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPositionCalculations
    {
        public int Id { get; set; }
        public int PositionId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorSid { get; set; }
        public string CreatorName { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleterSid { get; set; }
        public string DeleterName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> StateChangeDate { get; set; }
        public string StateChangerSid { get; set; }
        public string StateChangerName { get; set; }
        public string CatalogNumber { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> DeliveryTimeId { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> ProtectionFactId { get; set; }
        public string ProtectionFactCondition { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Provider { get; set; }
        public Nullable<decimal> RecomendedPrice { get; set; }
    
        public virtual ProjectCurrencies ProjectCurrencies { get; set; }
        public virtual ProjectCurrencies ProjectCurrencies1 { get; set; }
        public virtual ProjectPositionDeliveryTimes ProjectPositionDeliveryTimes { get; set; }
        public virtual ProjectPositions ProjectPositions { get; set; }
        public virtual ProjectProtectionFacts ProjectProtectionFacts { get; set; }
    }
}
