//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFiles
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int FolderId { get; set; }
        public byte[] fileDATA { get; set; }
        public bool Enabled { get; set; }
        public System.Guid FileGUID { get; set; }
        public string FileName { get; set; }
        public string CreatorSid { get; set; }
        public string CreatorName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string DeleterSid { get; set; }
        public string DeleterName { get; set; }
        public Nullable<System.DateTime> DeleterDate { get; set; }
        public Nullable<int> PreviousFileId { get; set; }
        public int VersionNumber { get; set; }
        public string PreviousFileGUID { get; set; }
    
        public virtual ProjectFolders ProjectFolders { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
