//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.ProjectConditionHistory = new HashSet<ProjectConditionHistory>();
            this.ProjectFiles = new HashSet<ProjectFiles>();
            this.ProjectPositions = new HashSet<ProjectPositions>();
            this.ProjectStateHistory = new HashSet<ProjectStateHistory>();
            this.ProjectTeams = new HashSet<ProjectTeams>();
            this.ProjectWorks = new HashSet<ProjectWorks>();
            this.ProjectMessages = new HashSet<ProjectMessages>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientInn { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> SaleDirectionId { get; set; }
        public Nullable<int> SaleSubjectId { get; set; }
        public Nullable<int> Probability { get; set; }
        public string ManagerSid { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> ManagerDepartmentId { get; set; }
        public string ManagerDepartmentName { get; set; }
        public string ManagerChiefSid { get; set; }
        public string ManagerChiefName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorSid { get; set; }
        public string CreatorName { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleterSid { get; set; }
        public string DeleterName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> StateChangeDate { get; set; }
        public string ChangerSid { get; set; }
        public string ChangerName { get; set; }
        public Nullable<bool> IsAuction { get; set; }
        public Nullable<System.DateTime> TkpDeadlineDate { get; set; }
        public string DeadlineDate { get; set; }
        public Nullable<System.DateTime> AuctionDeadlineDate { get; set; }
        public Nullable<int> ConditionId { get; set; }
        public Nullable<int> BusinessTargetId { get; set; }
        public string BusinessTargetName { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<bool> CurrentYearRealization { get; set; }
        public bool HasBudget { get; set; }
        public Nullable<int> ClientRelationshipId { get; set; }
        public string Comment { get; set; }
        public string AuctionNumber { get; set; }
        public string AuctionLink { get; set; }
        public Nullable<System.DateTime> ConditionChangeDate { get; set; }
        public string ConditionChangerSid { get; set; }
        public string ConditionChangerName { get; set; }
    
        public virtual ProjectBusinessTargets ProjectBusinessTargets { get; set; }
        public virtual ProjectClientRelationships ProjectClientRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectConditionHistory> ProjectConditionHistory { get; set; }
        public virtual ProjectConditions ProjectConditions { get; set; }
        public virtual ProjectCurrencies ProjectCurrencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFiles> ProjectFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPositions> ProjectPositions { get; set; }
        public virtual ProjectSaleDirections ProjectSaleDirections { get; set; }
        public virtual ProjectSaleSubjects ProjectSaleSubjects { get; set; }
        public virtual ProjectStates ProjectStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStateHistory> ProjectStateHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTeams> ProjectTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectWorks> ProjectWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMessages> ProjectMessages { get; set; }
    }
}
