//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectWorkStateHistory
    {
        public int Id { get; set; }
        public int WorkId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorSid { get; set; }
        public string CreatorName { get; set; }
        public string Comment { get; set; }
        public int StateId { get; set; }
    
        public virtual ProjectWorks ProjectWorks { get; set; }
        public virtual ProjectWorkStates ProjectWorkStates { get; set; }
    }
}
