//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeCalcDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpeCalcEntities1 : DbContext
    {
        public SpeCalcEntities1()
            : base("name=SpeCalcEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProjectClientRelationships> ProjectClientRelationships { get; set; }
        public virtual DbSet<ProjectConditions> ProjectConditions { get; set; }
        public virtual DbSet<ProjectFiles> ProjectFiles { get; set; }
        public virtual DbSet<ProjectFolders> ProjectFolders { get; set; }
        public virtual DbSet<ProjectPositionCalculations> ProjectPositionCalculations { get; set; }
        public virtual DbSet<ProjectPositionQuantityUnits> ProjectPositionQuantityUnits { get; set; }
        public virtual DbSet<ProjectPositions> ProjectPositions { get; set; }
        public virtual DbSet<ProjectProtectionFacts> ProjectProtectionFacts { get; set; }
        public virtual DbSet<ProjectRoles> ProjectRoles { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectSaleDirectionResponsibles> ProjectSaleDirectionResponsibles { get; set; }
        public virtual DbSet<ProjectSaleDirections> ProjectSaleDirections { get; set; }
        public virtual DbSet<ProjectSaleSubjects> ProjectSaleSubjects { get; set; }
        public virtual DbSet<ProjectTeams> ProjectTeams { get; set; }
        public virtual DbSet<ProjectWorkCalculations> ProjectWorkCalculations { get; set; }
        public virtual DbSet<ProjectWorkQuantityUnits> ProjectWorkQuantityUnits { get; set; }
        public virtual DbSet<ProjectWorks> ProjectWorks { get; set; }
    }
}
